---
- name: New play for apache
  hosts: servera
  tasks:
    - name: Install httpd & firewalld
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: present

    - name: Add new content in httpd  
      ansible.builtin.copy:
        content: "Welcome to redhat\n"
        dest: /var/www/html/index.html

    - name: Start firewall service
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Add http in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started  