---
- name: Configure motd
  hosts: servera
  vars:
    - system_owner: workstation.example.com
  tasks:
    - name: Configure motd
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644