---
- name: Task Failure 
  hosts: serverb
  ignore_errors: yes
  vars:
    web_package: http
    db_package: mariadb-server

  tasks:
    - name: Install {{ web_package }} package
      ansible.builtin.dnf:
        name: "{{ web_package }}"
        state: present

    - name: Install {{ db_package }} package
      ansible.builtin.dnf:
        name: "{{ db_package }}"
        state: present